### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by rockyluke** [getmillipede/maas#3]
I've some ideas
- [ ] add `<title>`
- [ ] add link to twitter
- [ ] add 'How to'
- [ ] add box to choose size and text

Thanks <3

**Comment by dustbyte** [comment]
I think I might create a landing page for the index and leave the api with a text/plain output, after all, all we want is a good old millipede.

**Comment by tusbar** [comment]
Maybe it could all be the same API, `Accept: text/plain` if you want `text/plain`.

Maybe also add a `format=txt` query string parameter.

**Comment by dustbyte** [comment]
For the first point, you may be right at first about the `Accept` header but I don't think it's a good idea for an API to serve a view, which is html's purpose.
The same thought applies to the second point but I'd also add that it's a bad solution for user experience.

I still think that a WebUI with a millipede generator HCI calling the API would be more beneficial.
What about creating millipede-webui?

**Comment by rockyluke** [comment]
api.millipede.io is ready :)

**Comment by dustbyte** [comment]
Wunderful, millipede-ui will come later today :+1:
